FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Areas/Backend/Controllers/AspNetProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SeguridadCiudadana.Fwk.Infrastructure.Data.Core;
using SeguridadCiudadana.Fwk.Application.Core.Services;
using SeguridadCiudadana.Fwk.Domain.Core;

namespace SeguridadCiudadana.Ftd.Presentation.Web.Areas.Backend.Controllers
{
    //[SeguridadCiudadanaAuthorize(Roles = "Root")]
    public class AspNetProfilesController : Controller
    {
        
        
        private readonly ISecurityAppService _securityAppService;

        private readonly SeguridadCiudadanaEntities _db;

        public AspNetProfilesController(ISecurityAppService securityAppService)
        {
            _securityAppService = securityAppService;
            _db = new SeguridadCiudadanaEntities();

        }

        // GET: AspNetProfiles
        public async Task<ActionResult> Index(bool? esTransaccionExitosa)
        {
            if (esTransaccionExitosa.HasValue && esTransaccionExitosa.Value)
                ViewBag.esTransaccionExitosa = true;
            //return View(_db.AspNetProfiles.Where(x => x.Activo));
            return View(_db.AspNetProfiles);
        }

        // GET: AspNetProfiles/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetProfiles aspNetProfiles = await _db.AspNetProfiles.FindAsync(id);
            if (aspNetProfiles == null)
            {
                return HttpNotFound();
            }
            return View(aspNetProfiles);
        }

        // GET: AspNetProfiles/Create
        public ActionResult Create()
        {
            var viewModel = new AspNetProfiles()
            {
                AspNetRoles = _db.AspNetRoles.Where(x => x.Activo).OrderBy(x => x.Name).ToList()
            };
            return View(viewModel);
        }

        // POST: AspNetProfiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AspNetProfiles aspNetProfiles)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var perfil = new AspNetProfiles
                    {
                        Id  = Guid.NewGuid().ToString(),
                        Name = aspNetProfiles.Name,
                        Activo = true,
                        AspNetRoles = new List<AspNetRoles>()
                    };

                    foreach (var item in aspNetProfiles.AspNetRoles.Where(p => p.IsSelected))
                    {
                        var rol = await _db.AspNetRoles.FindAsync(item.Id);
                        rol.AspNetProfiles.Add(perfil);
                    }

                    _db.AspNetProfiles.Add(perfil);
                    await _db.SaveChangesAsync();

                    return RedirectToAction("Index", new { esTransaccionExitosa = true });

                }
                catch (Exception ex)
                { }
            }

            return View(aspNetProfiles);
        }

        // GET: AspNetProfiles/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var perfil = await _db.AspNetProfiles.FindAsync(id);
            if (perfil == null)
            {
                return HttpNotFound();
            }
            var rolesIds = perfil.AspNetRoles.Select(r => r.Id);


            //Cargar todos los roles (para poder ser mostrados)
            perfil.AspNetRoles = _db.AspNetRoles.Where(x => x.Activo).ToList();

            //Poner como chequeado los que estan relacionados al perfil
            foreach (var r in perfil.AspNetRoles)
                r.IsSelected = rolesIds.Contains(r.Id);

            return View(perfil);

        }

        // POST: AspNetProfiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AspNetProfiles aspNetProfiles, string id)
        {
            if (ModelState.IsValid)
            {
                var perfil = await _db.AspNetProfiles.FindAsync(id);

                if (perfil != null)
                {
                    //GUARDAR LAS PROPIEDADES ESCALARES
                    //_db.Entry(perfil).CurrentValues.SetValues(aspNetProfiles);//fer

                    perfil.Name = aspNetProfiles.Name;
                                        
                    perfil.Activo = true;

                    foreach (var rol in aspNetProfiles.AspNetRoles)
                    {
                        #region ASOCIAR O ELIMINAR EL ROL
                        //ASOCIAR NUEVO ROL
                        if (rol.IsSelected)
                        {
                            if (perfil.AspNetRoles.All(r => r.Id != rol.Id))
                            {
                                var r = new AspNetRoles()
                                {
                                    Id = rol.Id 
                                };
                                _db.AspNetRoles.Attach(r);
                                perfil.AspNetRoles.Add(r);
                            }
                        }
                        //ELIMINAR ASOCIACION
                        else
                        {
                            var removedRol = perfil.AspNetRoles.SingleOrDefault(c => c.Id == rol.Id);
                            if (removedRol != null)
                                perfil.AspNetRoles.Remove(removedRol);
                        }
                        #endregion
                    }
                    _db.Entry(perfil).State = EntityState.Modified;
                    _db.SaveChanges();

                    #region ACTUALIZAR USUARIOS QUE TIENEN ESE PERFIL
                    var userList = _db.AspNetUsers.Where(x => x.AspNetProfiles.Any(p => p.Id == perfil.Id));

                    foreach (var usuario in userList.ToList())
                    {
                        foreach (var r in perfil.AspNetRoles.ToList())
                        {
                            if (perfil.AspNetRoles.Contains(r))
                            {
                                usuario.AspNetRoles.Add(r);
                            }
                            else
                            {
                                usuario.AspNetRoles.Remove(r);
                            }
                        }

                        foreach (var r in usuario.AspNetRoles.ToList())
                        {
                            if (!perfil.AspNetRoles.Contains(r))
                            {
                                usuario.AspNetRoles.Remove(r);
                            }
                        }
                        _db.Entry(usuario).State = EntityState.Modified;
                    }
                    _db.SaveChanges();
                    #endregion

                    return RedirectToAction("Index", new { esTransaccionExitosa = true });
                }
            }
            return View(aspNetProfiles);
        }

        // GET: AspNetProfiles/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetProfiles aspNetProfiles = await _db.AspNetProfiles.FindAsync(id);
            if (aspNetProfiles == null)
            {
                return HttpNotFound();
            }
            return View(aspNetProfiles);
        }

        // POST: AspNetProfiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            AspNetProfiles aspNetProfiles = await _db.AspNetProfiles.FindAsync(id);
            aspNetProfiles.Activo = false;
            _db.Entry(aspNetProfiles).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return RedirectToAction("Index", new { esTransaccionExitosa = true });
        }

        [HttpPost, ActionName("Suspender")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Suspender(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var perfil = await _db.AspNetProfiles.FindAsync(id);

            if (perfil == null)
            {
                return HttpNotFound();
            }

            perfil.Activo = false;
            _db.Entry(perfil).State = EntityState.Modified;
            await _db.SaveChangesAsync();

            return RedirectToAction("Index", new { esTransaccionExitosa = true });
        }

        [HttpPost, ActionName("Activar")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Activar(string id)
        {
            var perfil = await _db.AspNetProfiles.FindAsync(id);

            if (perfil == null)
            {
                return HttpNotFound();
            }

            perfil.Activo = true;
            _db.Entry(perfil).State = EntityState.Modified;
            await _db.SaveChangesAsync();

            return RedirectToAction("Index", new { esTransaccionExitosa = true });

        }

FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Areas/Backend/Views/AspNetProfiles/Create.cshtml
@model  SeguridadCiudadana.Fwk.Domain.Core.AspNetProfiles

@{
    ViewBag.Title = "Create";
}

<h2>Nuevo Perfil</h2>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.AntiForgeryToken()
        @Html.Partial("_CreateOrEdit", Model)
    </div>

    <hr style="border-top-color: black;">

    <div class="row">
        <div class="col-md-12" style="padding-left: 10px;">
            <input type="submit" value="Guardar" class="btn btn-success" />
            @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
}

FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Areas/Backend/Views/AspNetProfiles/Delete.cshtml
@model  SeguridadCiudadana.Fwk.Domain.Core.AspNetProfiles

@{
    ViewBag.Title = "Delete";
}

<h3>Confirma que desea borrar el perfil @Model.Name?</h3>

<hr style="border-top-color: black;">

<div>
    <hr />
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-danger" />
            @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Areas/Backend/Views/AspNetProfiles/Details.cshtml
@model  SeguridadCiudadana.Fwk.Domain.Core.AspNetProfiles

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AspNetProfiles</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id=Model.Id }, new { @class = "btn btn-default" })
    @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-default" }) 
</p>

FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Areas/Backend/Views/AspNetProfiles/Edit.cshtml
@model  SeguridadCiudadana.Fwk.Domain.Core.AspNetProfiles
@{
    ViewBag.Title = "Editar";
}

<h2>Editar Perfil</h2>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.AntiForgeryToken()
        @Html.HiddenFor(m=>m.Id)
        @Html.Partial("_CreateOrEdit", Model)
    </div>

    <hr style="border-top-color: black;">

    <div class="row">
        <div class="col-md-12" style="padding-left: 10px;">
            <input type="submit" value="Guardar" class="btn btn-success" />
            @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
}

FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Areas/Backend/Views/AspNetProfiles/Index.cshtml
@model IEnumerable<SeguridadCiudadana.Fwk.Domain.Core.AspNetProfiles>

@{
    ViewBag.Title = "Perfiles";
}

@if (ViewBag.esTransaccionExitosa != null && ViewBag.esTransaccionExitosa == true)
{
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-info alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <span class="glyphicon glyphicon-ok">
                    Transaccion realizada en forma exitosa.
                </span>
            </div>
        </div>
    </div>
}

<h2>Perfiles</h2>

<p>
    @Html.ActionLink("Nuevo Perfil de Usuario", "Create")
</p>

<hr style="border-top-color: black;">

@{var n = 1;}

<table class="table table-bordered table-striped" id="listado">
    <thead>
        <tr>
            <th style="text-align: center; width: 6rem;">
                @Html.DisplayName("Ord")
            </th>
            <th style="text-align: center;">
                @Html.DisplayName("Perfil")
            </th>
            <th style="text-align: center; width: 6rem;">
                @Html.DisplayName("Estado")
            </th>
            <th style="text-align: center; width: 6rem;"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td style="text-align: center;">
                    @n.ToString()
                    @{n++;}
                </td>
                <td>
                    @Html.ActionLink(item.Name, "Details", new { id = item.Id })
                </td>
                <td style="text-align: center; width: 8rem;">
                    @if (item.Activo)
                    {
                        <span class="label label-success label-size-normal">Activo</span>
                    }
                    else
                    {
                        <span class="label label-danger label-size-normal">Suspendido</span>
                    }
                </td>
                <td style="text-align: center; width: 15rem;">
                    @Html.ActionLink("Editar", "Edit", new { id = item.Id  }) |
                    @if (item.Activo)
                    {
                        using (Html.BeginForm("suspender", "AspNetProfiles", FormMethod.Post, new { id = "suspenderForm", @style = "display: inline;" }))
                        {
                            @Html.AntiForgeryToken()
                            <a href="javascript:submitSuspender('@item.Id');">Suspender</a>
                        }
                    }
                    else
                    {
                        using (Html.BeginForm("activar", "AspNetProfiles", FormMethod.Post, new { id = "activarForm", @style = "display: inline;" }))
                        {
                            @Html.AntiForgeryToken()
                            <a href="javascript:submitActivar('@item.Id');">Activar</a>
                        }
                    }
                </td>
            </tr>
                        }
    </tbody>

</table>

@section scripts
{

    <link href="~/Content/bootstrap.datatables.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.datatables-1.10.11.js"></script>
    <script src="~/Scripts/jquery.datatables-bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#listado').DataTable(
            {
                "ordering": false,
                "language": {
                    "lengthMenu": "Mostrando _MENU_ registros por pagina",
                    "zeroRecords": "No se encontraron registros",
                    "info": "Pagina _PAGE_ de _PAGES_",
                    "infoEmpty": "No hay registros",
                    "infoFiltered": "(filtered from _MAX_ total records)",
                    "paginate": {
                        "previous": "Anterior",
                        "next": "Siguiente"
                    },
                    "search": "Buscar"
                }
            });
        });

        function submitSuspender(id) {
            var input = document.createElement("input");
            input.setAttribute("type", "hidden");
            input.setAttribute("name", "id");
            input.setAttribute("value", id);
            document.getElementById("suspenderForm").appendChild(input);
            document.getElementById('suspenderForm').submit();
        }
        function submitActivar(id) {
            var input = document.createElement("input");
            input.setAttribute("type", "hidden");
            input.setAttribute("name", "id");
            input.setAttribute("value", id);
            document.getElementById("activarForm").appendChild(input);
            document.getElementById('activarForm').submit();
        }


    </script>
}

FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Areas/Backend/Views/AspNetProfiles/_CreateOrEdit.cshtml
@*@using PTP.Data*@
@model  SeguridadCiudadana.Fwk.Domain.Core.AspNetProfiles

<div class="row">
    <div class="col-md-12">
        <input type="submit" value="Guardar" class="btn btn-success" />
        @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
    </div>
</div>

<hr style="border-top-color: black;">

<div class="row">
    <div class="col-md-12">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    </div>

    <div class="col-md-5">
        <div class="form-group" style="padding-left: 10px; padding-right: 10px;">
            @Html.Label("Perfil", htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
</div>


<div class="row" style="margin-top:1rem;">
    <div class="col-md-12">
        <div class="form-group" style="padding-left: 10px; padding-right: 10px;">
            <h3>@Html.Label("Roles", null, htmlAttributes: new { @class = "control-label", @styles = "margin-top: 0rem;" })</h3>
            <div class="row">
                @Html.EditorFor(model => Model.AspNetRoles)
            </div>
            
            @Html.ValidationMessageFor(model => model.Name)
        </div>
    </div>
</div>