FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Areas/Backend/Controllers/AspNetUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Security.Claims;
using System.Web.Security;
using System.Data.Entity.Validation;
using System.Diagnostics;
using SeguridadCiudadana.Fwk.Application.Core.Services;
using SeguridadCiudadana.Fwk.Infrastructure.Data.Core;
using SeguridadCiudadana.Fwk.Domain.Core;
using SeguridadCiudadana.Ftd.Presentation.Web.Utils;
using SeguridadCiudadana.Ftd.Presentation.Web.Models;
using SeguridadCiudadana.Ftd.Presentation.Web.Resources;
using System.Configuration;
using SeguridadCiudadana.Fwk.Infrastructure.CrossCutting.Core.Mailing;
using SeguridadCiudadana.Fwk.Infrastructure.Crosscutting.Core.Logging;
using System.Net.Mail;
using SeguridadCiudadana.Fwk.Domain.Core.Enums;

namespace SeguridadCiudadana.Ftd.Presentation.Web.Areas.Backend.Controllers
{
    //[SeguridadCiudadanaAuthorize(Roles = "Root")]
    public class AspNetUsersController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        private readonly ISecurityAppService _securityAppService;
        private readonly IConfigurationAppService _configurationAppService;
        private readonly IAlertAppService _alertAppService;

        private readonly SeguridadCiudadanaEntities _db;

        public AspNetUsersController(ISecurityAppService securityAppService, IConfigurationAppService configurationAppService, IAlertAppService alertAppService)
        {
            _securityAppService = securityAppService;
            _configurationAppService = configurationAppService;
            _alertAppService = alertAppService;
            _db = new SeguridadCiudadanaEntities();

        }

        // GET: AspNetUsers
        //[CIMTUCAuthorize(Roles = "Usuarios-Listado, Root")]
        public async Task<ActionResult> Index(bool? esTransaccionExitosa)
        {
            if (esTransaccionExitosa.HasValue && esTransaccionExitosa.Value)
                ViewBag.esTransaccionExitosa = true;

            return View(_securityAppService.GetAllPersons());
            //return View(_db.AspNetUsers);
        }

        // GET: AspNetUsers/Details/5
        //[SeguridadCiudadanaAuthorize(Roles = "Usuarios-Listado, Root")]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //AspNetUsers aspNetUsers = await _managerAspNetUsers.GetByIdAsync(id);//fer
            AspNetUsers aspNetUsers = await _db.AspNetUsers.FindAsync(id);
            if (aspNetUsers == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUsers);
        }

        // GET: AspNetUsers/Create
        //[SeguridadCiudadanaAuthorize(Roles = "Usuarios-Alta, Root")]
        public ActionResult Create()
        {
            //Mostrar imagen por defecto
            Persona personasViewModel = new Persona();
            personasViewModel.AspNetUsers = new AspNetUsers();

            Bitmap img = new Bitmap(Server.MapPath("~/Content/user.png"));
            personasViewModel.ImagenBase64 = ImageUtils.ImageToBase64(img, ImageFormat.Png);
            personasViewModel.AspNetUsers.AspNetProfiles = _db.AspNetProfiles.Where(x => x.Activo).OrderBy(x => x.Name).ToList();

            LoadViewsBags("Formulario de Registro");

            if (User.Identity.IsAuthenticated)
            {
                personasViewModel.AspNetUsers.AgreeTerms = true;
                ViewBag.Titulo = "Crear Usuario";
            }
            return View(personasViewModel);
        }

        // POST: AspNetUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[SeguridadCiudadanaAuthorize(Roles = "Usuario-Crear, Root")]
        public async Task<ActionResult> Create(Persona model, FormCollection collection)
        {
            
            #region VALIDAR MAIL
            
            if (_db.personas.Any(x => x.Email.ToLower().Trim() == model.Email.ToLower().Trim()))
            {
                ModelState.AddModelError("Mail", "Este mail se encuentra asociado a otro usuario.");
            }

            #endregion

            #region PROCESAR IMAGEN
            Bitmap img;
            img = string.IsNullOrEmpty(model.PathImagen) ? new Bitmap(Server.MapPath("~/Content/user.png")) : new Bitmap(Server.MapPath(model.PathImagen));

            model.ImagenBase64 = ImageUtils.ImageToBase64(img, ImageFormat.Png);

            if (model.Imagen != null) //Guardar en carpeta temporal
            {
                model.PathImagen = GuardarImagen(model.Imagen, "Temp", "0");
                img = new Bitmap(Server.MapPath((string)model.PathImagen));
                model.ImagenBase64 = ImageUtils.ImageToBase64(img, ImageFormat.Png);
            }
            #endregion

            if (ModelState.IsValid)
            {
                #region CREAR PERSONA
                var persona = new Persona()
                {
                    Nombre = model.Nombre,
                    Apellido = model.Apellido,
                    Email = model.Email,
                    Documento = model.Documento,
                    TipoDocumento = int.Parse(collection[7]),
                    Genero = model.Genero,
                    FechaRegistracion = DateTime.Now,
                    FechaNacimiento = model.FechaNacimiento,
                    TelefonoCelular  = model.TelefonoCelular,
                    TelefonoOpcional = model.TelefonoOpcional,
                    Calle = model.Calle,
                    CodigoPostal = model.CodigoPostal,
                    PaisId = model.PaisId,
                    ProvinciaId = model.ProvinciaId,
                    LocalidadId = model.LocalidadId,
                };
                #endregion

                var user = new ApplicationUser { UserName = model.AspNetUsers.UserName, Email = model.Email};
                
                var result = await UserManager.CreateAsync(user, model.AspNetUsers.Password);
                if (result.Succeeded)
                {
                    var newUser = await _db.AspNetUsers.FindAsync(user.Id);
                    await UserManager.AddClaimAsync(newUser.Id , new Claim("active", "false"));

                    #region GUARDAR PERFILES Y USUARIOS
                    foreach (var item in model.AspNetUsers.AspNetProfiles.Where(p => p.IsSelected))
                    {
                        var perfil = await _db.AspNetProfiles.FindAsync(item.Id);
                        perfil.AspNetUsers.Add(newUser);
                        foreach (var rol in perfil.AspNetRoles)
                        {
                            var r = await _db.AspNetRoles.FindAsync(rol.Id);
                            r.AspNetUsers.Add(newUser);
                        }
                    }
                    #endregion

                    persona.AspNetUsers = newUser;
                    persona.UserId
                         = newUser.Id;

                    _db.personas.Add(persona);
                    
                    try
                    {
                        await _db.SaveChangesAsync();
                        await SendConfirmationMail(model.Email, user.Id);
                    }
                    catch (DbEntityValidationException dbEx)
                    {
                        foreach (var validationErrors in dbEx.EntityValidationErrors)
                        {
                            foreach (var validationError in validationErrors.ValidationErrors)
                            {
                                Trace.TraceInformation("Class: {0}, Property: {1}, Error: {2}",
                                    validationErrors.Entry.Entity.GetType().FullName,
                                    validationError.PropertyName,
                                    validationError.ErrorMessage);
                            }
                        }

                        throw;  // You can also choose to handle the exception here...
                    }
                   

                    #region MOVER ARCHIVOS
                    if (!string.IsNullOrEmpty(model.PathImagen) && model.PathImagen.StartsWith("\\Files\\Temp\\"))
                    {
                        var destPath = $"\\Files\\Usuarios\\{model.UserId}";
                        var fileName = Path.GetFileName(model.PathImagen);

                        string sourceFile = Server.MapPath(model.PathImagen);
                        string destinationFile = Server.MapPath(Path.Combine(destPath, fileName));

                        // Ensure that the target does not exist.
                        if (System.IO.File.Exists(destinationFile))
                            System.IO.File.Delete(destinationFile);

                        model.PathImagen = Path.Combine(destPath, fileName);

                        if (!Directory.Exists(destPath))
                            Directory.CreateDirectory(Server.MapPath(destPath));

                        // Move the file.
                        System.IO.File.Copy(sourceFile, destinationFile);
                    }
                    #endregion

                    _db.SaveChanges();
                    return RedirectToAction("Index", new { esTransaccionExitosa = true });
                }
                AddErrors(result);
            }
            LoadViewsBags("Formulario de Registro");
            

FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Areas/Backend/Views/AspNetUsers/Create.cshtml
@model  SeguridadCiudadana.Fwk.Domain.Core.Persona
@{
    ViewBag.Title = ViewBag.Titulo;
}

@using (Html.BeginForm("Create", "AspNetUsers", FormMethod.Post, new { id = "actorForm", enctype = "multipart/form-data" }))
{
    <div class="form-horizontal">
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        @Html.AntiForgeryToken()
        @Html.Partial("_CreateOrEdit", Model)
    </div>

    <hr style="border-top-color: black;">

    <div class="row">
        <div class="col-md-12" style="padding-left: 10px;">
            <input type="submit" value="Guardar" class="btn btn-success" />
            @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
}


@section scripts{

    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#vista-previa')
                        .attr('src', e.target.result)
                };
                reader.readAsDataURL(input.files[0]);
            }
        }

        $(function () {

            $('#FechaNacimiento').datepicker({
                dateFormat: "yy-mm-dd",
                changeMonth: true,
                changeYear: true,
                yearRange: "-115:-18", //18 years or older up until 115yo (oldest person ever, can be sensibly set to something much smaller in most cases)
                maxDate: "-18Y", //Will only allow the selection of dates more than 18 years ago, useful if you need to restrict this
                minDate: "-115Y"
            });

            $("#PaisId").change(function () {
                populateStates($("#PaisId").val());
            });
            $("#ProvinciaId").change(function () {
                populateCities($("#ProvinciaId").val());
            });

            $("#LocalidadId").change(function () {
                getPostalCode($("#LocalidadId").val());
                
            });
        });

        function populateStates(paisId) {
            var ddStates = document.getElementById("ProvinciaId");
            ddStates.options.length = 0;
            ddStates.options[0] = new Option("Cargando...");
            ddStates.selectedIndex = 0;
            ddStates.disabled = true;

            $.getJSON(
            '@Url.Action("GetStates")',
            { paisId: paisId },
            function (data) {
                if (data.length > 0) {
                    $.each(data, function (i, item) {
                        ddStates.options[i] = new Option(item.Descripcion, item.ProvinciaId);
                    });
                    ddStates.options[-1] = new Option("Seleccione...");
                    ddStates.selectedIndex = -1;
                }
                else {
                    ddStates.options.length = 0;
                }
                ddStates.disabled = false;
            });
        }

        function populateCities(provinciaId) {
            var ddCities = document.getElementById("LocalidadId");
            ddCities.options.length = 0;
            ddCities.options[0] = new Option("Cargando...");
            ddCities.selectedIndex = 0;
            ddCities.disabled = true;

            $.getJSON(
            '@Url.Action("GetCities")',
            { provinciaId: provinciaId },
            function (data) {
                if (data.length > 0) {
                    $.each(data, function (i, item) {
                        ddCities.options[i] = new Option(item.Descripcion, item.LocalidadId );

                        //if (i==0) {
                        //    document.getElementById("CodigoPostal").value = item.CodigoPostal;
                        //}
                    });
                    ddCities.options[-1] = new Option("Seleccione...");
                    ddCities.selectedIndex = -1;
                }
                else {
                    ddCities.options.length = 0;
                }
                ddCities.disabled = false;
            });
        }

        function getPostalCode(localidadId) {
            

            $.getJSON(
            '@Url.Action("GetPostalCode")',
            { localidadId: localidadId },
            function (data) {
                document.getElementById("CodigoPostal").value = data;
            });
        }

    </script>

}

FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Areas/Backend/Views/AspNetUsers/Edit.cshtml
@model  SeguridadCiudadana.Fwk.Domain.Core.Persona

<h2>Editar Usuario</h2>

@using (Html.BeginForm("Edit", "AspNetUsers", FormMethod.Post, new { id = "actorForm", enctype = "multipart/form-data" }))
{
    <div class="form-horizontal">
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        @Html.AntiForgeryToken()
        @Html.Partial("_CreateOrEdit", Model)
        @Html.HiddenFor(m=>m.PersonaId)
        @Html.HiddenFor(m => m.AspNetUsers.Id)
    </div>

    <hr style="border-top-color: black;">

    <div class="row">
        <div class="col-md-12" style="padding-left: 10px;">
            <input type="submit" value="Guardar" class="btn btn-success" />
            @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
}

@section scripts{

    @Scripts.Render("~/bundles/jqueryval")

                    <script type="text/javascript">

                            function readURL(input) {
                                if (input.files && input.files[0]) {
                                    var reader = new FileReader();
                                    reader.onload = function (e) {
                                        $('#vista-previa')
                                            .attr('src', e.target.result)
                                    };
                                    reader.readAsDataURL(input.files[0]);
                                }
                            }

                            $(function () {

                                $('#FechaNacimiento').datepicker({
                                    dateFormat: "yy-mm-dd",
                                    changeMonth: true,
                                    changeYear: true,
                                    yearRange: "-115:-18", //18 years or older up until 115yo (oldest person ever, can be sensibly set to something much smaller in most cases)
                                    maxDate: "-18Y", //Will only allow the selection of dates more than 18 years ago, useful if you need to restrict this
                                    minDate: "-115Y"
                                });

                                $("#PaisId").change(function () {
                                    populateStates($("#PaisId").val());
                                });
                                $("#ProvinciaId").change(function () {
                                    populateCities($("#ProvinciaId").val());
                                });

                                $("#LocalidadId").change(function () {
                                    getPostalCode($("#LocalidadId").val());

                                });
                            });

                            function populateStates(paisId) {
                                var ddStates = document.getElementById("ProvinciaId");
                                ddStates.options.length = 0;
                                ddStates.options[0] = new Option("Cargando...");
                                ddStates.selectedIndex = 0;
                                ddStates.disabled = true;

                                $.getJSON(
                                '@Url.Action("GetStates")',
                                { paisId: paisId },
                                function (data) {
                                    if (data.length > 0) {
                                        $.each(data, function (i, item) {
                                            ddStates.options[i] = new Option(item.Descripcion, item.ProvinciaId);
                                        });
                                        ddStates.options[-1] = new Option("Seleccione...");
                                        ddStates.selectedIndex = -1;
                                    }
                                    else {
                                        ddStates.options.length = 0;
                                    }
                                    ddStates.disabled = false;
                                });
                            }

                            function populateCities(provinciaId) {
                                var ddCities = document.getElementById("LocalidadId");
                                ddCities.options.length = 0;
                                ddCities.options[0] = new Option("Cargando...");
                                ddCities.selectedIndex = 0;
                                ddCities.disabled = true;

                                $.getJSON(
                                '@Url.Action("GetCities")',
                                { provinciaId: provinciaId },
                                function (data) {
                                    if (data.length > 0) {
                                        $.each(data, function (i, item) {
                                            ddCities.options[i] = new Option(item.Descripcion, item.LocalidadId );

                                            //if (i==0) {
                                            //    document.getElementById("CodigoPostal").value = item.CodigoPostal;
                                            //}
                                        });
                                        ddCities.options[-1] = new Option("Seleccione...");
                                        ddCities.selectedIndex = -1;
                                    }
                                    else {
                                        ddCities.options.length = 0;
                                    }
                                    ddCities.disabled = false;
                                });
                            }

                            function getPostalCode(localidadId) {


                                $.getJSON(
                                '@Url.Action("GetPostalCode")',
                                { localidadId: localidadId },
                                function (data) {
                                    document.getElementById("CodigoPostal").value = data;
                                });
                            }

                    </script>

}

FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Areas/Backend/Views/AspNetUsers/Index.cshtml
@model IEnumerable<SeguridadCiudadana.Fwk.Domain.Core.Persona>

@{
    ViewBag.Title = "Index";
}

@if (ViewBag.esTransaccionExitosa != null && ViewBag.esTransaccionExitosa == true)
{
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-info alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <i class="glyphicon glyphicon-ok"> </i>
                <span>
                    Transaccion realizada en forma exitosa.
                </span>
            </div>
        </div>
    </div>
}

<h2>Usuarios</h2>

<p>
    @Html.ActionLink("Nuevo Usuario", "Create")
</p>

<hr style="border-top-color: black;">


<table class="table table-bordered table-striped" id="listado">
    <thead>
        <tr>
            <th style="text-align: center; width: 6rem;">
                @Html.DisplayNameFor(model => model.TipoDocumento)
            </th>
            <th style="text-align: center; width: 6rem;">
                @Html.DisplayNameFor(model => model.Documento)
            </th>
            <th style="text-align: center; width: 25%;">
                @Html.DisplayName("Nombre y Apellido")
            </th>
            <th style="text-align: center; width: 15rem;">
                @Html.DisplayName("Usuario")
            </th>
            <th style="text-align: center; width: 25%;">
                @Html.DisplayName("Mail")
            </th>
            <th style="text-align: center; width: 8rem;">
                @Html.DisplayName("Perfiles")
            </th>
            <th style="text-align: center; width: 25%;"></th>
            <th style="text-align: center; width: 25%;"></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td style="text-align: center;">
                    @Enum.GetName(typeof(SeguridadCiudadana.Fwk.Domain.Core.Enums.TipoDocumento), item.TipoDocumento)
                </td>
                <td style="text-align: center;">
                   @Html.DisplayFor(modelItem => item.Documento)
                </td>
                <td>
                    @{
                        if (item.AspNetUsers != null)
                        {
                            var firstOrDefault = item.AspNetUsers.Persona.FirstOrDefault();
                            if (firstOrDefault != null)
                            {
                                @Html.ActionLink(firstOrDefault.NombreCompleto, "DatosUsuario", new { username = item.AspNetUsers.UserName })
                            }
                        }
                        else
                        {
                            @Html.Label(item.NombreCompleto)
                        }
                    }
                </td>
                <td>
                    @if (item.AspNetUsers != null)
                    {

                        @Html.ActionLink(item.AspNetUsers.UserName, "DatosUsuario", new { username = item.AspNetUsers.UserName })
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AspNetUsers.Email)
                </td>
                <td>
                    @if (item.AspNetUsers != null)
                    {
                        foreach (var perfil in item.AspNetUsers.AspNetProfiles.Where(p => p.Activo))
                        {
                            @*@Html.ActionLink(perfil.Name, "details", new { id = item.AspNetUsers.Id }, new { @style = "margin-left: 1rem;" })*@
                            @perfil.Name
                        }
                    }
                </td>
                <td style="text-align: center; width: 25%;">
                    @{ 
                        if (item.AspNetUsers != null)
                        {
                            if (item.AspNetUsers.AspNetUserClaims.Any(c => c.ClaimType == "active" && c.ClaimValue == "true"))
                            {
                            <span class="label label-success label-size-normal">Activo</span>
                            }
                            else
                            {
                            <span class="label label-danger label-size-normal">Suspendido</span>
                            }
                        }
                    }
                </td>
                <td style="text-align: center; width: 25%;">
                    @{ 
                        

                        <a href="@Url.Action("Edit", new { id = item.PersonaId  })" title="Editar" class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span></a>

                        if (item.AspNetUsers != null)  //if (User.IsInRole("ABM_Usuarios"))
                        {
                            using (Html.BeginForm("Dispositivos", "AspNetUsers", FormMethod.Post, new { id = "dispositivosForm", @style = "display: inline;" }))
                            {
                                @Html.AntiForgeryToken()
                                <a href="javascript:submitDispositivos('@item.AspNetUsers.Id');" title="Dispositivos" class="btn btn-default"><span class="glyphicon glyphicon-screenshot"></span></a>
                            }

                            if (item.AspNetUsers.AspNetUserClaims.Any(c => c.ClaimType == "active" && c.ClaimValue == "true"))
                            {
                                using (Html.BeginForm("suspender", "AspNetUsers", FormMethod.Post, new { id = "suspenderForm", @style = "display: inline;" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <a href="javascript:submitSuspender('@item.AspNetUsers.Id');" title="Suspender" class="btn btn-default"><span class="glyphicon glyphicon-remove-circle"></span></a>
                                }
                            }
                            else
                            {
                                using (Html.BeginForm("activar", "AspNetUsers", FormMethod.Post, new { id = "activarForm", @style = "display: inline;" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <a href="javascript:submitActivar('@item.AspNetUsers.Id');" title="Activar" class="btn btn-default"><span class="glyphicon glyphicon-ok-circle"></span></a>
                                }
                            }

                        }

                       }
                </td>
            </tr>
         }
    </tbody>
</table>
<hr />


@section scripts{
    <link href="~/Content/bootstrap.datatables.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.datatables-1.10.11.js"></script>
    <script src="~/Scripts/jquery.datatables-bootstrap.js"></script>


    <script type="text/javascript">
        $(document).ready(function () {
            $('#listado').DataTable(
            {
                "ordering": false,
                "language": {
                    "lengthMenu": "Mostrando _MENU_ registros por pagina",
                    "zeroRecords": "No se encontraron registros",
                    "info": "Pagina _PAGE_ de _PAGES_",
                    "infoEmpty": "No hay registros",
                    "infoFiltered": "(filtered from _MAX_ total records)",
                    "paginate": {
                        "previous": "Anterior",
                        "next": "Siguiente"
                    },
                    "search": "Buscar",
                    "scrollX": true
                }
            });
        });

        
    </script>
}

FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Areas/Backend/Views/AspNetUsers/MiPerfil.cshtml
@model  SeguridadCiudadana.Fwk.Domain.Core.Persona
@{
    ViewBag.Title = "Mi Perfil";
}

@if (ViewBag.esTransaccionExitosa != null && ViewBag.esTransaccionExitosa == true)
{
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-info alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <img src="~/Content/Images/success.png" class="header-image" />
                <span>
                    Transaccion realizada en forma exitosa.
                </span>
            </div>
        </div>
    </div>
}

<h2>Mi Perfil</h2>

@using (Html.BeginForm("MiPerfil", "AspNetUsers", FormMethod.Post, new { id = "actorForm", enctype = "multipart/form-data" }))
{
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.AntiForgeryToken()
        @Html.Partial("_CreateOrEditMiPerfil", Model)
        @Html.HiddenFor(m => m.PersonaId )
        @Html.HiddenFor(m => m.AspNetUsers.Id)
    </div>

    <hr style="border-top-color: black;">

    <div class="row">
        <div class="col-md-12" style="padding-left: 10px;">
            <input type="submit" value="Guardar" class="btn btn-success" />
            @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
}


@section scripts{

    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">

        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#vista-previa')
                        .attr('src', e.target.result)
                };
                reader.readAsDataURL(input.files[0]);
            }
        }

    </script>

}