FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Areas/Backend/Controllers/AlertaController.cs
using SeguridadCiudadana.Fwk.Application.Core.Services;
using SeguridadCiudadana.Fwk.Domain.Core;
using SeguridadCiudadana.Fwk.Domain.Core.Enums;
using SeguridadCiudadana.Fwk.Domain.Core.States.Alertas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SeguridadCiudadana.Ftd.Presentation.Web.Areas.Backend.Controllers
{
    public class AlertaController : Controller
    {
        private readonly IAlertAppService _alertAppService;
        private readonly ISecurityAppService _securityAppService;


        public AlertaController(IAlertAppService alertAppService, ISecurityAppService securityAppService)
        {
            _alertAppService = alertAppService;
            _securityAppService = securityAppService;

        }
        // GET: Backend/Alerta
        public ActionResult Index()
        {
            ViewBag.Operations = Enum.GetNames(typeof(Operacion)).ToList();
            var alertas = _alertAppService.GetTopFiveAlerts();
            return View(alertas);
        }

        // GET: Backend/Alerta/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Backend/Alerta/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Backend/Alerta/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Backend/Alerta/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Backend/Alerta/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Backend/Alerta/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Backend/Alerta/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //GetAllLocation - for fetch all the location from database and show in the view
        //Shows all the locations in default map here.
        public JsonResult GetAllLocation()
        {
            var v = this._alertAppService.GetTopFiveAlerts().Select(x => new { Id = x.AlertaId, Title = x.Dispositivo.DescripcionLargaDispositivo, Address = x.Direccion, ImagePath = "/Content/" + x.TipoAlerta + ".jpg", Latitud = x.Latitud, Longitud = x.Longitud }).ToList();
            return new JsonResult { Data = v, JsonRequestBehavior = JsonRequestBehavior.AllowGet };

        }
        //This method gets the markers info from database.
        public JsonResult GetMarkerData(int locationID)
        {

            var v = this._alertAppService.GetAlertsById(locationID).Select(x => new { Id = x.AlertaId, Title = x.Dispositivo.DescripcionLargaDispositivo, Address =  x.Direccion, ImagePath = "/Content/" + x.TipoAlerta+".jpg", Latitud = x.Latitud, Longitud = x.Longitud }).ToList();

            return new JsonResult { Data = v, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        
        public ActionResult AddAlertHistory(int? alertaId, int? estado, string observacion)
        {
                var a = this._alertAppService.GetAlertById(alertaId.Value);

                var alertaHistoria = new AlertaHistoria()
                {
                    Alerta = a,
                    FechaHora = DateTime.Now,
                    Estado = estado,
                    Observacion = observacion,
                    UserId = this._securityAppService.GetUserByName(User.Identity.Name).Id,
                    CurrentState = AlertaStateFactory.CreateState((Estado)estado.Value)
                };
            
                this._alertAppService.CreateAlertHistory(alertaHistoria);


                //return new JsonResult { Data = alertaHistoria, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
                return PartialView("History", _alertAppService.GetAlertById(alertaHistoria.AlertaId).AlertasHistoria);


        }


    }
}

FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Areas/Backend/Controllers/AspNetRolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;

using SeguridadCiudadana.Fwk.Application.Core.Services;
using SeguridadCiudadana.Fwk.Infrastructure.Data.Core;
using SeguridadCiudadana.Fwk.Domain.Core;

namespace SeguridadCiudadana.Ftd.Presentation.Web.Areas.Backend.Controllers
{
    //[CIMTUCAuthorize(Roles = "Root")]
    public class AspNetRolesController : Controller
    {

        private readonly ISecurityAppService _securityAppService;

        private readonly SeguridadCiudadanaEntities _db;

        public AspNetRolesController(ISecurityAppService securityAppService)
        {
            _securityAppService = securityAppService;
            _db = new SeguridadCiudadanaEntities();

        }

        // GET: AspNetRoles
        public async Task<ActionResult> Index(bool? esTransaccionExitosa)
        {
            if (esTransaccionExitosa.HasValue && esTransaccionExitosa.Value)
                ViewBag.esTransaccionExitosa = true;
            
            return View(_securityAppService.GetAllRoles());
        }

        // GET: AspNetRoles/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //AspNetRoles aspNetRoles = await _aspNetRolesAppService.GetByIdAsync(id);
            AspNetRoles aspNetRoles = await _db.AspNetRoles.FindAsync(id);
            if (aspNetRoles == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRoles);
        }

        // GET: AspNetRoles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AspNetRoles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AspNetRoles aspNetRoles)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    aspNetRoles.Id = Guid.NewGuid().ToString();
                    aspNetRoles.Activo = true;

                    //await _aspNetRolesAppService.CreateAsync(aspNetRoles);//fer
                    _securityAppService.CreateRol(aspNetRoles);

                    return RedirectToAction("Index", new { esTransaccionExitosa = true });
                }
                catch (Exception ex)
                { }
            }
            
            return View(aspNetRoles);
        }

        // GET: AspNetRoles/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //AspNetRoles aspNetRoles = await _aspNetRolesAppService.GetByIdAsync(id);//fer
            AspNetRoles aspNetRoles = await _db.AspNetRoles.FindAsync(id);

            if (aspNetRoles == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRoles);
        }

        // POST: AspNetRoles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AspNetRoles aspNetRoles)
        {
            if (ModelState.IsValid)
            {
                aspNetRoles.Activo = true;
                //await _aspNetRolesAppService.EditAsync(aspNetRoles);//fer
                _securityAppService.EditRol(aspNetRoles);

                return RedirectToAction("Index", new { esTransaccionExitosa = true });
            }
            return View(aspNetRoles);
        }

        // GET: AspNetRoles/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //AspNetRoles aspNetRoles = await _aspNetRolesAppService.GetByIdAsync(id); // fer
            AspNetRoles aspNetRoles = await _db.AspNetRoles.FindAsync(id);
            if (aspNetRoles == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRoles);
        }

        // POST: AspNetRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            //AspNetRoles aspNetRoles = await _aspNetRolesAppService.GetByIdAsync(id); //fer
            AspNetRoles aspNetRoles = await _db.AspNetRoles.FindAsync(id);
            //await _aspNetRolesAppService.DeleteAsync(aspNetRoles); //fer
            _securityAppService.DeleteRol(aspNetRoles);

            return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Suspender")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Suspender(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //AspNetRoles aspNetRole = await _aspNetRolesAppService.GetByIdAsync(id);
            AspNetRoles aspNetRole = await _db.AspNetRoles.FindAsync(id);

            if (aspNetRole == null)
            {
                return HttpNotFound();
            }

            //Validar si hay algun usuario activo en este rol
            if (aspNetRole.AspNetUsers.Where(u => u.AspNetUserClaims.Any(c => c.ClaimType == "active" && c.ClaimValue == "true")).Count() > 0)
            {
                ModelState.AddModelError("", "El rol no se puede deshabilitar porque hay usuarios activos asociados a él.");
            }
            else
            {
                aspNetRole.Activo = false;
                //await _aspNetRolesAppService.EditAsync(aspNetRole); //fer
                _securityAppService.EditRol(aspNetRole);
            }
            return View("index", _securityAppService.GetAllRoles());
        }

        [HttpPost, ActionName("Activar")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Activar(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //AspNetRoles aspNetRole = await _aspNetRolesAppService.GetByIdAsync(id);
            AspNetRoles aspNetRole = await _db.AspNetRoles.FindAsync(id);

            if (aspNetRole == null)
            {
                return HttpNotFound();
            }

            aspNetRole.Activo = true;
            //await _aspNetRolesAppService.EditAsync(aspNetRole);
            _securityAppService.EditRol(aspNetRole);

            return View("index", _securityAppService.GetAllRoles());
        }

        protected override void Dispose(bool disposing)
        {
            //if (disposing)
            //{
            //    managerDispose();
            //}
            base.Dispose(disposing);
        }
    }
}

FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Views/Shared/AccessDenied.cshtml
@model System.Web.Mvc.HandleErrorInfo

@{
    ViewBag.Title = "Acceso denegado";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">Acceso denegado.</h2>

FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Views/Shared/_AdminLteBreadcrumb.cshtml
@* 
 This breadcrumb partial is meant to be dropped into the top of the main content page
    and uses the AdminLte.Breadcrumb class to dynamically build the breadcrumb per page
*@

@if (ViewBag.Breadcrumb != null)
{
    <ol class="breadcrumb">
        @foreach (Crumb crumb in ViewBag.Breadcrumb)
        {
            <li>
                @if (crumb.HasLink)
                {
                    <a href="@crumb.Link">
                        @if (crumb.HasIcon)
                        {
                            <i class="fa @crumb.Icon"></i>
                        }

                        <span>@crumb.Text</span>
                    </a>
                }
                else
                {
                    if (crumb.HasIcon)
                    {
                        <i class="fa @crumb.Icon"></i>
                    }

                    <span>@crumb.Text</span>
                }
            </li>
        }
    </ol>
}

FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Views/Shared/_AdminLteLayout.cshtml
@* 
 This is the main dashboard layout that creates the AdminLTE look and feel
    It includes all of the relevant CSS and Js in this project and across CDNs around the web for optimal load times
    TODO: Use this layout in your views by either setting the "Layout" property 
    or changing your  _ViewStart.cshtml to use this layout
 *@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @*TODO: Change App name*@
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    @*Source Sans Pro from Google Fonts*@
    <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic" rel="stylesheet" />
    @*Bundle CSS, assuming includes Bootstrap CSS *@
    @Styles.Render("~/Content/css")
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Morris chart -->
    <link href="@Url.Content("~/Scripts/AdminLTE/plugins/morris/morris.css")" rel="stylesheet" type="text/css" />
    <!-- jvectormap -->
    <link href="@Url.Content("~/Scripts/AdminLTE/plugins/jvectormap/jquery-jvectormap-1.2.2.css")" rel="stylesheet" type="text/css" />
    <!-- Daterange picker -->
    <link href="@Url.Content("~/Scripts/AdminLTE/plugins/daterangepicker/daterangepicker-bs3.css")" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="@Url.Content("~/Content/AdminLTE/AdminLTE.min.css")" rel="stylesheet" type="text/css" />
    @*TODO: AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load.*@
    <link href="@Url.Content("~/Content/AdminLTE/skins/_all-skins.min.css")" rel="stylesheet" type="text/css" />

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="skin-blue">

    <div class="wrapper">

        @Html.Partial("_AdminLteTopMenu")
        <!-- Left side column. contains the logo and sidebar -->
        @Html.Partial("_AdminLteLeftMenu")
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    @ViewBag.Title
                    <small>@ViewBag.TitleSmall</small>
                </h1>
                @Html.Partial("_AdminLteBreadcrumb")
            </section>
            <!-- Main content -->
            <section class="content">
                @RenderBody()
            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.0
            </div>
            <strong>Copyright &copy; 2014-2015 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights reserved.
        </footer>
    </div><!-- ./wrapper -->
    @* Bundles assume jquery 2.1.3 and Bootstrap 3 *@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <!-- FastClick -->
    <script src="@Url.Content("~/Scripts/AdminLTE/plugins/fastclick/fastclick.min.js")"></script>
    <!-- AdminLTE App -->
    <script src="@Url.Content("~/Scripts/AdminLTE/app.js")" type="text/javascript"></script>
    <!-- Sparkline -->
    <script src="@Url.Content("~/Scripts/AdminLTE/plugins/sparkline/jquery.sparkline.min.js")" type="text/javascript"></script>
    <!-- jvectormap -->
    <script src="@Url.Content("~/Scripts/AdminLTE/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/AdminLTE/plugins/jvectormap/jquery-jvectormap-world-mill-en.js")" type="text/javascript"></script>
    <!-- daterangepicker -->
    <script src="@Url.Content("~/Scripts/AdminLTE/plugins/daterangepicker/daterangepicker.js")" type="text/javascript"></script>
    <!-- datepicker -->
    <script src="@Url.Content("~/Scripts/AdminLTE/plugins/datepicker/bootstrap-datepicker.js")" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="@Url.Content("~/Scripts/AdminLTE/plugins/iCheck/icheck.min.js")" type="text/javascript"></script>
    <!-- SlimScroll 1.3.0 -->
    <script src="@Url.Content("~/Scripts/AdminLTE/plugins/slimScroll/jquery.slimscroll.min.js")" type="text/javascript"></script>
    <!-- ChartJS 1.0.1 -->
    <script src="@Url.Content("~/Scripts/AdminLTE/plugins/chartjs/Chart.min.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/SeguridadCiudadana.js")" type="text/javascript"></script>
      

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC7_Gu6-anwPHEmFcosvsp51XpqWFiJl5Y&callback=initMap"
            type="text/javascript"></script>

    @* AngularJS library *@
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.6/angular.js"></script>
    @* google map*@
    <script src="//cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.js"></script>
    <script src="//rawgit.com/angular-ui/angular-google-maps/2.0.X/dist/angular-google-maps.js"></script>

    

    <script src="@Url.Content("~/Scripts/maps.js")"></script>  

    @RenderSection("scripts", required: false)
</body>
</html>

FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FrontEnd/SeguridadCiudadana.Ftd.Presentation.Web/SeguridadCiudadana.Ftd.Presentation.Web/Views/Shared/_MenuPartial.cshtml
<ul class="sidebar-menu">
    @*@if (Request.IsAuthenticated)
    {*@
        
        <li class="header">Seguridad</li>
        @*if (User.IsInRole("ABM_Roles"))
        {*@
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-key"></i> <span>Roles</span> <i class="fa fa-angle-left pull-right"></i>
                    </a>
                    <ul class="treeview-menu">

                        <li><a href="@Url.Action("Create", "AspNetRoles", new { Area = "Backend" }, null)"><i class="fa fa-circle-o"></i> Crear Rol</a></li>
                        <li><a href="@Url.Action("Index", "AspNetRoles", new { Area = "Backend" }, null)"><i class="fa fa-circle-o"></i> Lista de Roles</a></li>


                    </ul>
                </li>

        @*}
        if (User.IsInRole("ABM_Perfiles"))
        {*@
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-key"></i> <span>Perfiles</span> <i class="fa fa-angle-left pull-right"></i>
                    </a>
                    <ul class="treeview-menu">
                
                            <li><a href="@Url.Action("Create", "AspNetProfiles", new { Area = "Backend" }, null)"><i class="fa fa-circle-o"></i> Crear Perfil</a></li>
                            <li><a href="@Url.Action("Index", "AspNetProfiles", new { Area = "Backend" }, null)"><i class="fa fa-circle-o"></i> Lista de Perfiles</a></li>
                    
              
               
                    </ul>
                </li>
        @*}*@
        @*if (User.IsInRole("ABM_Usuarios"))
        {*@
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-key"></i> <span>Usuarios</span> <i class="fa fa-angle-left pull-right"></i>
                    </a>
                    <ul class="treeview-menu">
                
                            <li><a href="@Url.Action("Create", "AspNetUsers", new { Area = "Backend" }, null)"><i class="fa fa-circle-o"></i> Crear Usuario</a></li>
                            <li><a href="@Url.Action("Index", "AspNetUsers", new { Area = "Backend" }, null)"><i class="fa fa-circle-o"></i> Lista de Usuarios</a></li>
               
               
                    </ul>
                </li>

                

        @*}*@

        <li class="header">Alertas</li>
            <li><a href="@Url.Action("Index", "Alerta", new { Area = "Backend" }, null)"><i class="glyphicon glyphicon-map-marker"></i> Panel de Alertas</a></li>
        


        @*}*@
</ul>